使用新增API   compiler.hooks.emit.tap 解决 webpack4 下报错
searchfe/sw-register-webpack-plugin pull request #21
Opened 2019-03-26 05:23 UTC by qq282126990

2019-03-27 09:02 UTC, zoumiaojiang requested changes

2019-03-27 09:02 UTC, zoumiaojiang commented on index.js
> +    compiler.hooks.emit.tap('emit', (compilation, callback) => {
这个地方可能有个问题，如果现在还有开发者在用 webpack3.x，那这个插件就不能正常运行了吧？最好的方式是做一个嗅探处理，将回调的函数抽离出来比如：
```js
let emitCallback = function (compilation, callback) {
    // ... 
}
```
然后区分一下 webpack3 和 webpack4 去调用 `compiler.plugin('emit', emitCallback)` 或 `compiler.hooks.emit.tap('emit', emitCallback)`

2019-03-27 09:02 UTC, zoumiaojiang commented on index.js
> +const babel = require("@babel/core");
统一单引号哈

2019-03-27 09:02 UTC, zoumiaojiang commented on index.js
> -        callback();
这个 callback 不能删掉吧？emit 是个异步的过程，需要保证回调的执行。

2019-03-27 15:52 UTC, qq282126990 commented on index.js
> -        callback();
webpack4 下 callback 是一个 undefined ，调用会报错

2019-03-28 07:22 UTC, zoumiaojiang requested changes

2019-03-28 07:22 UTC, zoumiaojiang commented on index.js
> +                    source () {
这个项目是遵循百度编码规范的，需要在提交之前跑一遍 fecs 工具检查哈，不然的话构建会报错的 https://travis-ci.org/lavas-project/sw-register-webpack-plugin

2019-03-28 07:22 UTC, zoumiaojiang commented on index.js
> -        callback();
嗯，因为你用的不是 async，可以做个判断 `callback && callback()` 兼容 webpack 3.x

2019-03-28 15:39 UTC, qq282126990 commented on index.js
> +                    source () {
已经跑过了，但是检测 node_modules 里面的文件会报错


![image](https://user-images.githubusercontent.com/26755049/55171047-a83b5500-51b2-11e9-8b74-4744db2a0913.png)

2019-04-24 10:38 UTC, closed without merging